name: .NET unit tests

on:
  pull_request_target:
  push:

jobs:
  run_net_tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./news-scrapper

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./news-scrapper/news-scrapper.infrastructure.unit-tests
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
      with:
        reports: './news-scrapper.infrastructure.unit-tests/TestResults/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        verbosity: 'Info'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: coveragereport
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coveragereport