name: Prettify code

on: 
  push:
  pull_request: 

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TEST_TOKEN }}

      - name: add file
        run: touch test.file

#       - name: prettify code
#         run: |
#           npm install
#           npm ci
#           npm run prettier

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: prettify code
